<a href="https://colab.research.google.com/github/GEOFFREY-MO/My-data/blob/main/Computational.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**TASK**

You are supposed to perform the following tasks and save them with your name and registration
number “YOUR NAME- REG NO.) e.g. JOHN MAINA-4581.

1. Using Microsoft excel the table attached shows the temperature of the covid -19 patients seen in a
certain hospital in Kimathi University. Use the data in the table given to carry out practical for this
task.

2. View and write the data as an array or a matrix of 5x5 and each patient as a variable .
Find the mean temperature of each patient and output the remarks as: if the patient average
temperature is equal or more than 37 degrees Celsius, give remark as ‘’admit’’ and any temperature
below 37 degree Celsius, remark as ‘’discharge’’.

3. Import the excel sheet in your notebook and do the above also.

4. Download the code as Python(.py)

5. Send your code and results to the email bsmmpkom@gmail.com

![excel1.JPG]()

***The above figure is the image of an excel sheet we are going to compare it with the yellow column of the mean or average  as named on the excel sheet of a python code below***.

Let now import numpy libray and declare all patient variables

then disply the results interms of the mean and compare it with our excel sheet above.

In [ ]:
import numpy as np
A,B,C,D,E=np.array([[40,37,39,37,30],[39,35,37,40,37.5],[37,36,40,39,41],[36,38,39,38,39],[38,39,37,39,39]])
print(A,B,C,D,E)

[40. 37. 39. 37. 30.] [39.  35.  37.  40.  37.5] [37. 36. 40. 39. 41.] [36. 38. 39. 38. 39.] [38. 39. 37. 39. 39.]

In [ ]:
Q = A,B,C,D,E

In [ ]:
Q

(array([40., 37., 39., 37., 30.]),
 array([39. , 35. , 37. , 40. , 37.5]),
 array([37., 36., 40., 39., 41.]),
 array([36., 38., 39., 38., 39.]),
 array([38., 39., 37., 39., 39.]))

In [ ]:
mean=np.mean(Q,axis=1)

In [ ]:
mean

array([36.6, 37.7, 38.6, 38. , 38.4])

As you can see the results of the mean or average of the code above is exactly

as it is in the yellow column of excel sheet.

Lets now apply **where()** condition since we are dealing with an array with mulptiple  columns.

In [ ]:
patients = mean[np.where(np.logical_and(mean>37,mean<50))]
patients2 = mean[np.where(np.logical_and(mean>10,mean<37))]
print('Discharge',patients2)
print('Admit',patients)

Discharge [36.6]
Admit [37.7 38.6 38.  38.4]

**Import the excel sheet in a csv file to your notebook to do the above also**

In [ ]:
import pandas as pd
data = pd.read_csv('computational.csv')
data.head()

FileNotFoundError: ignored

In [ ]:
mean=np.mean(data,axis=1)

/usr/local/lib/python3.9/dist-packages/numpy/core/fromnumeric.py:3472: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  return mean(axis=axis, dtype=dtype, out=out, **kwargs)

the output above is invalid since our data is unclean

so let us go ahead and clean it as possible

In [ ]:
data.rename(columns={'Unnamed: 0':'number','Unnamed: 1':'petients','Unnamed: 2':'day_1','Unnamed: 3':'day_2','Unamed: 4':'day_3','Unnamed: 5':'day_4','Unnamed: 6':'day_5','Unnamed: 7':'average','Unnamed: 8':'remarks'},inplace=True)
data.head()

,number,petients,Temperature( in degrees Celsius),day_2,Unnamed: 4,day_4,day_5,average,remarks
0,NaN,NaN,Day 1,Day 2,Day 3,Day 4,Day 5,Average,Remarks
1,1.0,Patient A,40,37,39,37,30,36.6,DISCHANGE
2,2.0,Patient B,39,35,37,40,37.5,37.7,ADMIT
3,3.0,Patient C,37,36,40,39,41,38.6,ADMIT
4,4.0,Patient D,36,38,39,38,39,38,ADMIT

In [ ]:
data.rename(columns={'Temperature( in degree Celsius)':'day_1'})

,number,petients,Temperature( in degrees Celsius),day_2,Unnamed: 4,day_4,day_5,average,remarks
0,NaN,NaN,Day 1,Day 2,Day 3,Day 4,Day 5,Average,Remarks
1,1.0,Patient A,40,37,39,37,30,36.6,DISCHANGE
2,2.0,Patient B,39,35,37,40,37.5,37.7,ADMIT
3,3.0,Patient C,37,36,40,39,41,38.6,ADMIT
4,4.0,Patient D,36,38,39,38,39,38,ADMIT
5,5.0,Patient E,38,39,37,39,39,38.4,ADMIT

In [ ]:
data=data.drop(['number','petients','average','remarks'],axis=1)

In [ ]:
data.head(2)

  Temperature( in degrees Celsius)  day_2 Unnamed: 4  day_4  day_5
0                            Day 1  Day 2      Day 3  Day 4  Day 5
1                               40     37         39     37     30
2                               39     35         37     40   37.5
3                               37     36         40     39     41
4                               36     38         39     38     39

In [ ]:
data= data.drop(labels=0,axis=0)

In [ ]:
data.head()

  Temperature( in degrees Celsius) day_2 Unnamed: 4 day_4 day_5
1                               40    37         39    37    30
2                               39    35         37    40  37.5
3                               37    36         40    39    41
4                               36    38         39    38    39
5                               38    39         37    39    39

In [ ]:
mean=data.mean(axis=1)
mean

0    36.6
1    37.7
2    38.6
3    38.0
4    38.4
dtype: float64